language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - extra-android-m2repository
    - android-24

jdk:
  - oraclejdk8

script: "./gradlew build"

branches:
  except:
    - gh-pages